### ISSUE TITLE
TypeError: Argument 3 passed to OCA\Zammad\Service\ZammadAPIService::getNotifications() must be of the type int or null, string given

### ISSUE THREAD

**Issue by drebs** [nextcloud/integration_zammad#34]
Hello, dear Zammad Integration devs!

I'm getting the following error when running Nextcloud's `cron.php`:

```
TypeError: Argument 3 passed to OCA\Zammad\Service\ZammadAPIService::getNotifications() must be of the type int or null, string given, called in                                                    
/var/www/cloud.example.org/apps/integration_zammad/lib/Service/ZammadAPIService.php on line 113 and defined in /var/www/cloud.example.org/apps/integration_zammad/lib/Service/ZammadAPIService.php:165  
Stack trace:                                                                                                                                                                                        
#0 /var/www/cloud.example.org/apps/integration_zammad/lib/Service/ZammadAPIService.php(113): OCA\Zammad\Service\ZammadAPIService->getNotifications()                                                  
#1 /var/www/cloud.example.org/apps/integration_zammad/lib/Service/ZammadAPIService.php(87): OCA\Zammad\Service\ZammadAPIService->checkOpenTicketsForUser()                                            
#2 /var/www/cloud.example.org/lib/private/User/Manager.php(551): OCA\Zammad\Service\ZammadAPIService->OCA\Zammad\Service\{closure}()                                                                  
#3 /var/www/cloud.example.org/apps/integration_zammad/lib/Service/ZammadAPIService.php(88): OC\User\Manager->callForAllUsers()                                                                        
#4 /var/www/cloud.example.org/apps/integration_zammad/lib/BackgroundJob/CheckOpenTickets.php(57): OCA\Zammad\Service\ZammadAPIService->checkOpenTickets()                                             
#5 /var/www/cloud.example.org/lib/public/BackgroundJob/Job.php(79): OCA\Zammad\BackgroundJob\CheckOpenTickets->run()                                                                                  
#6 /var/www/cloud.example.org/lib/public/BackgroundJob/TimedJob.php(95): OCP\BackgroundJob\Job->execute()                                                                                             
#7 /var/www/cloud.example.org/cron.php(151): OCP\BackgroundJob\TimedJob->execute()                                                                                                                    
#8 {main}
```

Environment info:

- Operating System: Debian 11.5 (Bullseye)
- PHP: 7.4.30
- Nextcloud: 24.0.5
- integration_zammad: 1.0.4
- Zammad: 5.2.2-10

Please let me know if there's more info I can provide.

Thank you for this nice app!

**Comment by eneiluj** [comment]
Thanks for the bug report! Could you check v1.1.1 which contains a fix?
