### ISSUE TITLE
ValueError: The arguments array must contain 2 items, 1 given

### ISSUE THREAD

**Issue by asaage** [nextcloud/integration_zammad#41]
I'm geting following error occasionally from my cronjob.
Since this only happens on Instances where the zammad_integration is installed i figured i might report it here.
Not sure, what the zammad-notifier actually does - i never got notifications about zammad-tickets from nextcloud and there is no such thing in personal-settings. I just use the dashboard-widget and the search - both work fine.

```
ValueError: The arguments array must contain 2 items, 1 given in /var/www/nc/lib/private/L10N/L10NString.php:88
Stack trace:
#0 /var/www/nc/lib/private/L10N/L10NString.php(88): vsprintf()
#1 /var/www/nc/lib/private/L10N/L10N.php(126): OC\L10N\L10NString->__toString()
#2 /var/www/nc/lib/private/L10N/LazyL10N.php(55): OC\L10N\L10N->n()
#3 /var/www/nc/apps/integration_zammad/lib/Notification/Notifier.php(92): OC\L10N\LazyL10N->n()
#4 /var/www/nc/lib/private/Notification/Manager.php(368): OCA\Zammad\Notification\Notifier->prepare()
#5 /var/www/nc/apps/notifications/lib/MailNotifications.php(198): OC\Notification\Manager->prepare()
#6 /var/www/nc/apps/notifications/lib/MailNotifications.php(168): OCA\Notifications\MailNotifications->sendEmailToUser()
#7 /var/www/nc/apps/notifications/lib/BackgroundJob/SendNotificationMails.php(49): OCA\Notifications\MailNotifications->sendEmails()
#8 /var/www/nc/lib/public/BackgroundJob/Job.php(78): OCA\Notifications\BackgroundJob\SendNotificationMails->run()
#9 /var/www/nc/lib/public/BackgroundJob/TimedJob.php(103): OCP\BackgroundJob\Job->start()
#10 /var/www/nc/lib/public/BackgroundJob/TimedJob.php(93): OCP\BackgroundJob\TimedJob->start()
#11 /var/www/nc/cron.php(152): OCP\BackgroundJob\TimedJob->execute()
#12 {main}
```
Environment info:

Operating ubuntu 20.4
PHP: 8.1
Nextcloud: 26
integration_zammad: 2.0.3

**Comment by julien-nc** [comment]
Thanks for the bug report. It should be fixed in the next release. I guess the plural translation was misused.
